[project]
name = "doc-correction"
version = "0.1.0"
description = ""
authors = [
    {name = "alwaysmavs",email = "beingswu@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy (<2.0)",
    "torch (>=2.8.0,<3.0.0)",
    "torchvision (>=0.23.0,<0.24.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "scikit-image (>=0.25.2,<0.26.0)",
    "timm (>=1.0.20,<2.0.0)",
    "opencv-python-headless (<4.12)"
]

[tool.poetry]
package-mode = false
packages = [{include = "doc_correction", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
